### ISSUE TITLE
Moving to GitHub LNP-WG org

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/ln-types#14]
Copy of my message to the common group:

> I think I have to multiply entities 🙁
> 
> The problem is that in rust world you have to maintain small libraries (called “crates”) to have a modular design.
> 
> But rust crate not necessarily equals to a git repo. Today at LNP/BP Association we have >50 of rust crates to maintain, and it will be a crazy overload to have each one as a standalone repo. So for me, until now, Git repo was a unit of code access rights (the needs of the level of peer review) and logical architecture - while rust crates was a way of actual code modularization. This was solved through rust “cargo workspaces”, which allow to maintain multiple crates inside a single repo in an efficient manner.
> 
> Unfortunatelly, I came to a situation, when some rust logically-related crates (like lightning_encoding and lnp2p) stored in the same repo ( lnp-core ), become too distant in their rust dependency hierarchy, having crates from other repos inbetween themselves - which resulted in inabulity to have a single Cargo.lock file per repo. Thus, they have to be split into separate repositories for now - and we have to multiply the number of git repositories, which is very unfortunatelly.
> 
> Another dimension to that problem is the fact that GitHub org can have only up to 6 pinned repos, grabbing attention of independent contributors. In LNP-BP GitHub org we have more than 6 already, especially if I will split lnp-core repo into multiple ones. We had to separate before other GitHub orgs from LNP-BP (for RGB, networking, storm etc); now it seems the time has come for LNP (lightning-related repos).
>
> So from today I will create a LNP-WG GitHub org and move all lightning-related crates to it, there splitting lnp-core into two repos, one for lightning_encoding and the other one for the rest of lnp-core. LNP Node will also be relocated to LNP-WG.

I would like to propose to move also this repo to `https://github.com/LNP-WG`. What do you think?

**Comment by Kixunil** [comment]
I don't have right to transfer ownership, so I can't do it. Anyway, I don't mind going along with transfer much but we should try to find ways to avoid it in the future to not mess with stability too much.

**Comment by dr-orlovsky** [comment]
I think this is the last transfer - that github org is fully dedicated to LN. I will check why you can't do the transfer

**Comment by dr-orlovsky** [comment]
You should be able to do it now. It was not about the permissions at the destinations, but about the permissions in the source.

**Comment by dr-orlovsky** [comment]
@Kixunil if it will save some of your time I can move the repo myself, if you ok with that

**Comment by Kixunil** [comment]
Oh, this got forgotten during my busy/sick period. Done.
