### ISSUE TITLE
Should we sanity-check NodeId?

### ISSUE THREAD

**Issue by Kixunil** [LNP-BP/ln-types#4]
Currently `NodeId` can be created from arbitrary bytes but perhaps we should at least sanity-check the zeroth byte to be 0x02 or 0x03.

**Comment by Kixunil** [comment]
I found an interesting reason to do checking. If node ID is guaranteed to begin with 0x02 or 0x03 we could define this very compact binary serialization of `P2PAddress`

`TAG|BIT_PADDING|PARITY|X_COORD|PORT|HOST`

Where TAG is either:

0 - IPv4 address -> HOST is 4B
1 - IPv6 address -> HOST is 2B
2 - Onion V3 address -> HOST is 34B
3 - hostname - HOST starts with 4B address length followed by the hostname bytes

`TAG` is 4 bits, `PARITY` is 1 bit, `BIT_PADDING` is 3 bits

We could also play around to make sure the values are 32-bit aligned.

**Comment by Kixunil** [comment]
@dr-orlovsky if you could provide some feedback on this it'd be helpful.

**Comment by Kixunil** [comment]
Decided to go for it.

**Comment by dr-orlovsky** [comment]
Sorry for slow reaction; I am really very much "under water these days"...

There are several things to consider and discuss in this regard. The first one, is should we rely on host names? DNSs are known to be well censorable...

I had my previous work on universal binary encoding for addresses which is a part of `inet_addr` crate for now. You may be interested in how I tried to address this question in https://github.com/internet2-org/rust-internet2/blob/master/addr/src/encoding.rs. I had no goal of making "binary" encoding compact, but rather fixed-length and `Copy`able, i.e fast and no-std. I think speed is more important with client-side-validation than saving few bytes of data.

**Comment by Kixunil** [comment]
Host names are already used in P2P addresses, so I think they have to be implemented.

Either way, I think doing sanity checks gives us more flexibility.

**Comment by dr-orlovsky** [comment]
I am clearly up for this high-performant sanity checks. Also I think it will be nice to have this second type (additional to those from `inet_addr`) which will support DNS names.
